# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aparcamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('accesible', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, default='', max_length=200)),
                ('via', models.CharField(blank=True, default='', max_length=100)),
                ('localidad', models.CharField(blank=True, default='', max_length=100)),
                ('provincia', models.CharField(blank=True, default='', max_length=30)),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=10)),
                ('barrio', models.CharField(blank=True, default='', max_length=200)),
                ('distrito', models.CharField(blank=True, default='', max_length=200)),
                ('latitud', models.CharField(blank=True, default='', max_length=200)),
                ('longitud', models.CharField(blank=True, default='', max_length=200)),
                ('telefono', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('aparcamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aparcamientos.Aparcamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default='1')),
                ('color', models.CharField(default='black', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Guardado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('aparcamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aparcamientos.Aparcamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('enlace', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aparcamientos', models.ManyToManyField(to='aparcamientos.Aparcamiento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pagina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aparcamientos.Usuario'),
        ),
        migrations.AddField(
            model_name='guardado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aparcamientos.Usuario'),
        ),
        migrations.AddField(
            model_name='estilo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estilos', to='aparcamientos.Usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aparcamientos.Usuario'),
        ),
    ]
