# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0002_auto_20170521_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardado',
            name='nombre_pagina',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='aparcamientos',
            field=models.ManyToManyField(related_name='usuarios', to='aparcamientos.Aparcamiento'),
        ),
    ]
