# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0004_auto_20170521_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 21, 11, 31, 34, 78829, tzinfo=utc)),
        ),
    ]
