# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0005_auto_20170521_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 21, 12, 14, 25, 260368, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 21, 12, 14, 25, 258417, tzinfo=utc)),
        ),
    ]
